"""
M5Stack Core 2 - UIFlow2 Application
Generated by UIFlow2 GUI Web IDE

IMPORTANT: Uses M5UI (m5ui + lvgl) library - NOT M5GFX
Features:
- WiFi connectivity from SD card config
- MQTT integration
- SD card file reading
- Multi-page UI with LVGL
"""

import os, sys, io
import M5
from M5 import BtnA
from M5 import BtnB
from M5 import BtnC
import m5ui
import lvgl as lv
from hardware import sdcard
import time
import network
import json
from umqtt.simple import MQTTClient
# import urequests  # Not available on M5Stack - commented out
import uhashlib
import ubinascii


class LoadingOverlay:
  """Reusable loading overlay with dimmed background, centered box, label and spinner"""
  
  def __init__(self, parent):
    """Create loading overlay on the specified parent page
    
    Args:
      parent: The parent LVGL object (typically a page) to attach the overlay to
    """
    # Create full-screen overlay with semi-transparent background
    self.overlay = lv.obj(parent)
    self.overlay.set_size(320, 240)  # Full screen
    self.overlay.set_pos(0, 0)
    self.overlay.set_style_bg_color(lv.color_hex(0x000000), 0)
    self.overlay.set_style_bg_opa(150, 0)  # Semi-transparent black
    self.overlay.set_style_border_width(0, 0)
    self.overlay.add_flag(lv.obj.FLAG.HIDDEN)  # Hide by default
    
    # Create centered loading box
    self.box = lv.obj(self.overlay)
    self.box.set_size(200, 150)
    self.box.align(lv.ALIGN.CENTER, 0, 0)
    self.box.set_style_bg_color(lv.color_hex(0xFFFFFF), 0)
    self.box.set_style_bg_opa(255, 0)
    self.box.set_style_border_color(lv.color_hex(0xCCCCCC), 0)
    self.box.set_style_border_width(2, 0)
    self.box.set_style_radius(10, 0)
    self.box.set_style_pad_all(20, 0)
    
    # Create label centered at top of box
    self.label = lv.label(self.box)
    self.label.set_text("Loading...")
    self.label.set_style_text_color(lv.color_hex(0x000000), 0)
    self.label.align(lv.ALIGN.TOP_MID, 0, 10)
    
    # Create spinner centered in box
    self.spinner = lv.spinner(self.box)
    self.spinner.set_size(60, 60)
    self.spinner.align(lv.ALIGN.CENTER, 0, 10)
  
  def show(self, text="Loading..."):
    """Show the loading overlay with specified text
    
    Args:
      text: The text to display in the loading label (default: "Loading...")
    """
    self.label.set_text(text)
    self.overlay.remove_flag(lv.obj.FLAG.HIDDEN)
  
  def hide(self):
    """Hide the loading overlay"""
    self.overlay.add_flag(lv.obj.FLAG.HIDDEN)
  
  def set_text(self, text):
    """Update the loading text without hiding/showing
    
    Args:
      text: The new text to display
    """
    self.label.set_text(text)



# UI Components (global - used across multiple functions)
dashboard_page = None  # type: m5ui.M5Page
github_page = None  # type: m5ui.M5Page
menu_page = None  # type: m5ui.M5Page
settings_page = None  # type: m5ui.M5Page
khadamaty_page = None  # type: m5ui.M5Page
github_page_list = None  # type: m5ui.M5List
github_page_text = None  # type: m5ui.M5TextItem
msgboxError = None  # type: m5ui.M5Msgbox
msgboxErrorMSGLBL = None  # type: m5ui.M5TextItem
msgboxErrorOKBTN = None  # type: m5ui.M5Button
loadingOverlay = None  # type: LoadingOverlay
github_page_title = None  # type: m5ui.M5Label
github_page_icon = None  # type: m5ui.M5Image
dashboard_page_title = None  # type: m5ui.M5Label
menu_page_title = None  # type: m5ui.M5Label
menu_page_settings_btn = None  # type: m5ui.M5Button
menu_page_khadamaty_btn = None  # type: m5ui.M5Button
settings_page_title = None  # type: m5ui.M5Label
settings_page_brightness_label = None  # type: m5ui.M5Label
settings_page_brightness_slider = None  # type: lv.slider
settings_page_volume_label = None  # type: m5ui.M5Label
settings_page_volume_slider = None  # type: lv.slider
khadamaty_page_title = None  # type: m5ui.M5Label
dashboard_page_label_wifi_status = None  # type: m5ui.M5Label
dashboard_page_label_mqtt_status = None  # type: m5ui.M5Label
dashboard_page_label_msg_count = None  # type: m5ui.M5Label

dashboard_page_label_ip_address = None  # type: m5ui.M5Label
dashboard_page_label_wifi_strength = None  # type: m5ui.M5Label
dashboard_page_label_battery = None  # type: m5ui.M5Label

# Network and Configuration (global - shared state)
wlan_sta = None  # type: network.WLAN
mqtt_client = None  # type: MQTTClient
wifiCredsJSON = None  # type: list
mqttCredsJSON = None  # type: dict
mqttMessages = None
pageIndex = None  # type: int
settingsJSON = None  # type: dict

# Screen power management
SCREEN_BRIGHTNESS_NORMAL = 200  # Full brightness (will be overridden by settings)
SCREEN_BRIGHTNESS_DIM = 30  # Dimmed brightness
SCREEN_DIM_TIMEOUT = 30  # Dim after 30 seconds
SCREEN_OFF_TIMEOUT = 120  # Turn off after 2 minutes
last_activity_time = None  # type: float

# Audio settings
SPEAKER_VOLUME = 8  # Default volume (0-11, will be overridden by settings)


def reportError(errorMessage):
  """Display error message in UI msgbox"""
  global msgboxError, msgboxErrorMSGLBL, github_page_title
  print('Error:', errorMessage)
  msgboxErrorMSGLBL.set_text(str(errorMessage))
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, False)
  # github_page_title.set_text(str(errorMessage))

def showLoading(show, title):
  """Show/hide loading indicator with spinner"""
  global loadingOverlay
  if show:
    print('Loading:', title)
    loadingOverlay.show(str(title))
    M5.update()  # Force UI refresh to show loading
  else:
    print('Loading complete')
    loadingOverlay.hide()
    M5.update()  # Force UI refresh to hide loading

def checkTime(x):
  """Check if current time is divisible by x (for periodic tasks)"""
  # No globals needed - pure function
  return (time.time()) % (int(x)) == 0


def wakeScreen():
  """Wake screen and reset inactivity timer"""
  global last_activity_time
  last_activity_time = time.time()
  M5.Display.setBrightness(SCREEN_BRIGHTNESS_NORMAL)
  print('Screen woke up')


def readSDFile(fileName, returnJSON):
  """
  Read file from SD card
  Args:
    fileName: Name of file in /sd/ directory
    returnJSON: If True, parse as JSON and return dict/list, else return string
  Returns:
    Parsed JSON object or string, None on error
  """
  # No globals needed - all variables are local
  showLoading(True, f'Loading {fileName}')
  try:
    with open('/sd/' + str(fileName), 'r') as ffile:
      fileLines = ffile.readlines()
    
    fileString = ''
    for line in fileLines:
      if len(line.strip()) > 0:
        fileString += line.strip()
    
    fileString = fileString.strip()
    returnValue = json.loads(fileString) if returnJSON else fileString
    print(f'Successfully loaded {fileName}')
  except Exception as e:
    print(f'ERROR in readSDFile: {e}')
    sys.print_exception(e)
    reportError(f'Failed to load {fileName}: {e}')
    returnValue = [] if returnJSON else None
  
  showLoading(False, '')
  return returnValue


def loadSettings():
  """Load settings from SD card with defaults"""
  global settingsJSON, SCREEN_BRIGHTNESS_NORMAL, SPEAKER_VOLUME
  
  settings = readSDFile('settings.json', True)
  created_defaults = False
  
  if not settings:
    # Default settings
    settings = {
      'max_brightness': 200,  # 0-255, minimum 127 (50%)
      'volume': 8  # 0-11, 0 is mute
    }
    created_defaults = True
    print('Using default settings (file not found)')
  
  # Ensure brightness is at least 50% (127)
  if settings.get('max_brightness', 200) < 127:
    settings['max_brightness'] = 127
  
  # Ensure volume is in valid range
  if settings.get('volume', 8) < 0:
    settings['volume'] = 0
  elif settings.get('volume', 8) > 11:
    settings['volume'] = 11
  
  settingsJSON = settings
  SCREEN_BRIGHTNESS_NORMAL = settings['max_brightness']
  SPEAKER_VOLUME = settings['volume']
  
  # Save default settings to SD card if we created them
  if created_defaults:
    saveSettings()
    print('Created default settings.json')
  
  print(f'Settings loaded: brightness={SCREEN_BRIGHTNESS_NORMAL}, volume={SPEAKER_VOLUME}')
  return settings


def saveSettings():
  """Save settings to SD card"""
  global settingsJSON
  
  try:
    if settingsJSON is None:
      return
    
    # Convert to JSON string
    json_str = json.dumps(settingsJSON)
    
    # Write to SD card
    with open('/sd/settings.json', 'w') as f:
      f.write(json_str)
    
    print(f'Settings saved: {settingsJSON}')
    
  except Exception as e:
    print(f'ERROR saving settings to SD: {e}')
    sys.print_exception(e)


def connectWifi(credentials):
  """
  Connect to WiFi using credentials from config
  Args:
    credentials: List of dicts with 'ssid' and 'password' keys
  """
  global wlan_sta
  
  # Build WiFi credentials map (local variable)
  wifi_map = {}
  for cred in credentials:
    wifi_map[cred['ssid']] = cred['password']
    showLoading(True, f"Checking: {cred['ssid']}")
    time.sleep(1)
  
  wlan_sta.config(reconnects=5)
  wlan_sta.config(dhcp_hostname='m5stack')
  
  # Scan and connect to available network
  showLoading(True, 'Scanning for networks...')
  while not wlan_sta.isconnected():
    for sta_record in wlan_sta.scan():
      ssid = sta_record[0].decode()
      if ssid in wifi_map:
        wlan_sta.active(False)
        wlan_sta.active(True)
        showLoading(True, f'Connecting to {ssid}')
        wlan_sta.connect(ssid, wifi_map[ssid])
        time.sleep(5)
        if wlan_sta.isconnected():
          print(f'Connected to {ssid}')
          showLoading(True, f'Connected: {ssid}')
          time.sleep(2)
          return
  


def updateGitHubList():
  """Update github_page_list with cached GitHub messages"""
  global github_page_list, mqttMessages
  
  try:
    # Clear existing list items
    github_page_list.clean()
    
    # Add cached messages to list (using simple m5ui method for better performance)
    if mqttMessages:
      for msg in mqttMessages:
        # Get display text from lines array
        if 'lines' in msg and len(msg['lines']) > 0:
          display_text = '\n'.join(msg['lines'])
        else:
          display_text = f"{msg.get('repository', 'Unknown')} - {msg.get('type', 'event')}"
        
        # Get colors from message
        text_color = int(msg.get('color', '0x000000'), 16) if isinstance(msg.get('color'), str) else msg.get('color', 0x000000)
        bg_color = int(msg.get('bgColor', '0xffffff'), 16) if isinstance(msg.get('bgColor'), str) else msg.get('bgColor', 0xffffff)
        
        # Add text to list with colors using simple m5ui method (much faster)
        label = github_page_list.add_text(display_text[:350], text_c=text_color, bg_c=bg_color)
        
        # Add 2px bottom margin to create spacing between items
        try:
          label.set_style_margin_bottom(2, 0)
        except:
          pass
        
    print(f'Updated github_page_list with {len(mqttMessages) if mqttMessages else 0} messages')
    
  except Exception as e:
    print(f'ERROR in updateGitHubList: {e}')
    sys.print_exception(e)

def loadMQTTMessages():
  """Load MQTT messages from SD card"""
  global github_page_title
  
  messages = readSDFile('mqtt-messages.json', True)
  if messages:
    # Limit to 8 messages for consistency and performance
    messages = messages[:5]
    github_page_title.set_text('MQTT Messages Loaded')
  return messages


def mqtt_callback(topic, msg):
  """Handle incoming MQTT messages"""
  print(f'MQTT Message - Topic: {topic.decode()}, Message: {msg.decode()}')
  handleMQTTMessage(topic.decode(), msg.decode())


def handleMQTTMessage(topic, message):
  """
  Process received MQTT messages
  Args:
    topic: The MQTT topic as string
    message: The message payload as string
  """
  global github_page_title, dashboard_page_label_mqtt_status, mqttMessages
  
  print(f'Processing MQTT - Topic: {topic}, Message: {message}')
  
  try:
    # Try to parse message as JSON
    msg_data = json.loads(message)
    
    # Check if this is a GitHub event message
    if isinstance(msg_data, dict) and msg_data.get('messageType') == 'event' and msg_data.get('messageGroup') == 'github':
      handleGitHubMessage(msg_data)
    else:
      # Handle other message types
      if isinstance(msg_data, dict):
        display_text = f"Topic: {topic}\n"
        for key, value in msg_data.items():
          display_text += f"{key}: {value}\n"
        dashboard_page_label_mqtt_status.set_text(display_text[:100])
      else:
        dashboard_page_label_mqtt_status.set_text(f"{topic}:\n{str(msg_data)[:80]}")
      
      # github_page_title.set_text(f"Latest: {topic}")
    
  except json.JSONDecodeError:
    # Message is not JSON, display as plain text
    dashboard_page_label_mqtt_status.set_text(f"{topic}:\n{message[:80]}")
    # github_page_title.set_text(f"Msg: {message[:20]}")
  except Exception as e:
    print(f'ERROR in handleMQTTMessage: {e}')
    sys.print_exception(e)


def handleGitHubMessage(msg_data):
  """
  Handle GitHub event messages with caching and deduplication
  Args:
    msg_data: Parsed message data dict
  """
  global mqttMessages, github_page_title
  
  try:
    # Extract unique ID
    msg_id = msg_data.get('id')
    if not msg_id:
      print('WARNING: GitHub message has no id field')
      return
    
    # Wake screen on new message
    wakeScreen()
    
    # Play notification sound
    playNotificationSound(msg_data)
    
    # Initialize mqttMessages if needed
    if mqttMessages is None:
      mqttMessages = []
    
    # Remove existing message with same ID (to override)
    mqttMessages = [m for m in mqttMessages if m.get('id') != msg_id]
    
    # Add new message at the beginning (latest first)
    mqttMessages.insert(0, msg_data)
    
    # Keep only last 8 messages (reduced from 15 for better performance)
    mqttMessages = mqttMessages[:5]
    
    # Save to SD card
    saveMQTTMessagesToSD()
    
    # Update the github list with latest messages
    updateGitHubList()
    
    # Update UI
    if 'lines' in msg_data and len(msg_data['lines']) > 0:
      display_text = '\n'.join(msg_data['lines'][:3])  # Show first 3 lines
      # github_page_title.set_text(display_text[:50])
    # else:
      # github_page_title.set_text(f"GitHub: {msg_data.get('repository', 'event')}")
    
    print(f"GitHub message cached: ID={msg_id}, Total messages={len(mqttMessages)}")
    
  except Exception as e:
    print(f'ERROR in handleGitHubMessage: {e}')
    sys.print_exception(e)


def saveMQTTMessagesToSD():
  """Save cached MQTT messages to SD card"""
  global mqttMessages
  
  try:
    if mqttMessages is None:
      return
    
    # Convert to JSON string
    json_str = json.dumps(mqttMessages)
    
    # Write to SD card
    with open('/sd/mqtt-messages.json', 'w') as f:
      f.write(json_str)
    
    print(f'Saved {len(mqttMessages)} messages to SD card')
    
  except Exception as e:
    print(f'ERROR saving MQTT messages to SD: {e}')
    sys.print_exception(e)


def connectMQTT():
  """Connect or reconnect to MQTT broker"""
  global mqtt_client, mqttCredsJSON, wlan_sta
  
  if not mqttCredsJSON:
    print('No MQTT credentials available')
    return False
  
  if not wlan_sta.isconnected():
    print('WiFi not connected, cannot connect to MQTT')
    return False
  
  try:
    showLoading(True, 'Connecting to MQTT...')
    
    # Close existing connection if any
    if mqtt_client:
      try:
        mqtt_client.disconnect()
      except:
        pass
    
    # Create new MQTT client
    mqtt_client = MQTTClient(
      mqttCredsJSON['client'],
      mqttCredsJSON['server'],
      port=int(mqttCredsJSON['port']),
      user=mqttCredsJSON['username'],
      password=mqttCredsJSON['password'],
      keepalive=1000,
      ssl=True,
      ssl_params={"server_hostname": mqttCredsJSON['server']}
    )
    mqtt_client.set_callback(mqtt_callback)
    mqtt_client.connect()
    
    # Subscribe to topic
    topic = mqttCredsJSON.get('topic', 'm5stack-notifications/github/all')
    mqtt_client.subscribe(topic)
    print(f'MQTT connected and subscribed to {topic}')
    showLoading(False, '')
    return True
    
  except Exception as e:
    print(f'ERROR: MQTT connection failed: {e}')
    sys.print_exception(e)
    showLoading(False, '')
    return False


def playNotificationSound(msg_data):
  """Play notification sound based on message status and conclusion"""
  
  try:
    # Set speaker to maximum volume for notifications
    M5.Speaker.setVolume(11)
    
    status = msg_data.get('status')
    conclusion = msg_data.get('conclusion')
    
    if status == 'completed' and conclusion == 'success':
      # Happy sound - loud cheerful ascending melody with longer tones
      M5.Speaker.tone(440, 300)  # A
      time.sleep(0.3)
      M5.Speaker.tone(523, 300)  # C
      time.sleep(0.3)
      M5.Speaker.tone(659, 300)  # E
      time.sleep(0.3)
      M5.Speaker.tone(784, 500)  # G (high)
      time.sleep(0.5)
      M5.Speaker.tone(784, 300)  # G (high) repeat
      time.sleep(0.3)
      M5.Speaker.tone(659, 400)  # E
    elif status == 'completed' and conclusion != 'success':
      # Sad sound - loud descending tones with much longer duration
      M5.Speaker.tone(523, 400)  # C
      time.sleep(0.4)
      M5.Speaker.tone(440, 400)  # A
      time.sleep(0.4)
      M5.Speaker.tone(392, 400)  # G
      time.sleep(0.4)
      M5.Speaker.tone(330, 500)  # E (low)
      time.sleep(0.5)
      M5.Speaker.tone(262, 600)  # C (low)
    else:
      # Regular notification - loud distinct pattern with longer tones
      M5.Speaker.tone(659, 300)  # E
      time.sleep(0.3)
      M5.Speaker.tone(784, 300)  # G
      time.sleep(0.3)
      M5.Speaker.tone(659, 300)  # E
      time.sleep(0.4)
      M5.Speaker.tone(784, 500)  # G
    
    print(f'Played notification sound: status={status}, conclusion={conclusion}')
    
  except Exception as e:
    print(f'ERROR playing notification sound: {e}')
    sys.print_exception(e)


def playClickSound():
  """Play button click sound"""
  global SPEAKER_VOLUME
  
  try:
    M5.Speaker.setVolume(SPEAKER_VOLUME)
    M5.Speaker.tone(1000, 50)
  except Exception as e:
    print(f'ERROR playing click sound: {e}')


# Commented out - urequests not available on M5Stack
# def generateHmacToken(secret_key, message):
#   """
#   Generate HMAC-SHA256 token for API authentication
#   
#   Args:
#     secret_key: Secret key as string
#     message: Message to sign (typically timestamp or request data)
#   
#   Returns:
#     Base64 encoded HMAC token as string
#   """
#   try:
#     # Convert secret key and message to bytes if they're strings
#     if isinstance(secret_key, str):
#       secret_key = secret_key.encode('utf-8')
#     if isinstance(message, str):
#       message = message.encode('utf-8')
#     
#     # Create HMAC-SHA256 hash
#     hmac = uhashlib.sha256(secret_key)
#     hmac.update(message)
#     
#     # Get digest and encode as base64
#     digest = hmac.digest()
#     token = ubinascii.b2a_base64(digest).decode('utf-8').strip()
#     
#     return token
#   except Exception as e:
#     print(f'ERROR generating HMAC token: {e}')
#     sys.print_exception(e)
#     return None


# Commented out - urequests not available on M5Stack
# def apiRequestWithHmac(url, secret_key, method='GET', payload=None, headers=None, message=None):
#   """
#   Submit API request with HMAC bearer token authentication
#   
#   Args:
#     url: API endpoint URL
#     secret_key: Secret key for HMAC generation
#     method: HTTP method (GET, POST, PUT, DELETE, etc.)
#     payload: Request body data (dict or string)
#     headers: Additional headers (dict)
#     message: Custom message to sign (default: current timestamp)
#   
#   Returns:
#     Response object from urequests, or None on error
#   """
#   try:
#     # Generate message to sign (default to timestamp)
#     if message is None:
#       message = str(int(time.time()))
#     
#     # Generate HMAC token
#     token = generateHmacToken(secret_key, message)
#     if not token:
#       print('ERROR: Failed to generate HMAC token')
#       return None
#     
#     # Prepare headers
#     request_headers = {
#       'Authorization': f'Bearer {token}',
#       'Content-Type': 'application/json'
#     }
#     
#     # Add custom headers if provided
#     if headers:
#       request_headers.update(headers)
#     
#     # Convert payload to JSON if it's a dict
#     if payload and isinstance(payload, dict):
#       payload = json.dumps(payload)
#     
#     # Make the request
#     print(f'Making {method} request to {url}')
#     
#     if method.upper() == 'GET':
#       response = urequests.get(url, headers=request_headers)
#     elif method.upper() == 'POST':
#       response = urequests.post(url, headers=request_headers, data=payload)
#     elif method.upper() == 'PUT':
#       response = urequests.put(url, headers=request_headers, data=payload)
#     elif method.upper() == 'DELETE':
#       response = urequests.delete(url, headers=request_headers)
#     else:
#       print(f'ERROR: Unsupported HTTP method: {method}')
#       return None
#     
#     print(f'Response status: {response.status_code}')
#     return response
#     
#   except Exception as e:
#     print(f'ERROR in apiRequestWithHmac: {e}')
#     sys.print_exception(e)
#     return None


# Event Handlers
def msgboxErrorOKBTN_released_event(event_struct):
  """Handle error dialog OK button click"""
  global msgboxError
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, True)


def btnA_wasClicked_event(state):
  """Handle Button A click - switch to dashboard page"""
  global dashboard_page
  playClickSound()
  wakeScreen()
  dashboard_page.screen_load()

def btnB_wasClicked_event(state):
  """Handle Button B click - switch to github page"""
  global github_page
  playClickSound()
  wakeScreen()
  github_page.screen_load()

def btnC_wasClicked_event(state):
  """Handle Button C click - switch to menu page"""
  global menu_page
  playClickSound()
  wakeScreen()
  menu_page.screen_load()


def menu_settings_btn_clicked_event(event_struct):
  """Handle settings button click in menu"""
  global settings_page
  playClickSound()
  wakeScreen()
  settings_page.screen_load()

def menu_khadamaty_btn_clicked_event(event_struct):
  """Handle khadamaty button click in menu"""
  global khadamaty_page
  playClickSound()
  wakeScreen()
  khadamaty_page.screen_load()

def msgboxErrorOKBTN_event_handler(event_struct):
  """LVGL event handler wrapper for error OK button"""
  # No globals needed - delegates to msgboxErrorOKBTN_released_event
  event = event_struct.code
  if event == lv.EVENT.RELEASED:
    msgboxErrorOKBTN_released_event(event_struct)
  return

def settings_brightness_slider_event(event_struct):
  """Handle brightness slider value change"""
  global settingsJSON, SCREEN_BRIGHTNESS_NORMAL, settings_page_brightness_slider, settings_page_brightness_label
  
  event = event_struct.code
  if event == lv.EVENT.VALUE_CHANGED:
    try:
      value = settings_page_brightness_slider.get_value()
      # Ensure minimum 50% (127)
      if value < 127:
        value = 127
        settings_page_brightness_slider.set_value(value, 0)
      
      settingsJSON['max_brightness'] = value
      SCREEN_BRIGHTNESS_NORMAL = value
      settings_page_brightness_label.set_text(f'Max Brightness: {int(value/255*100)}%')
      
      # Apply immediately
      M5.Display.setBrightness(value)
      
      # Save to SD card
      saveSettings()
      
      print(f'Brightness updated to {value}')
    except Exception as e:
      print(f'ERROR in brightness slider: {e}')
      sys.print_exception(e)

def settings_volume_slider_event(event_struct):
  """Handle volume slider value change"""
  global settingsJSON, SPEAKER_VOLUME, settings_page_volume_slider, settings_page_volume_label
  
  event = event_struct.code
  if event == lv.EVENT.VALUE_CHANGED:
    try:
      value = settings_page_volume_slider.get_value()
      settingsJSON['volume'] = value
      SPEAKER_VOLUME = value
      
      # Update label
      if value == 0:
        settings_page_volume_label.set_text('Volume: Muted')
      else:
        settings_page_volume_label.set_text(f'Volume: {int(value/11*100)}%')
      
      # Play test sound
      M5.Speaker.setVolume(value)
      M5.Speaker.tone(1000, 100)
      
      # Save to SD card
      saveSettings()
      
      print(f'Volume updated to {value}')
    except Exception as e:
      print(f'ERROR in volume slider: {e}')
      sys.print_exception(e)

def setup():
  """Initialize M5Stack, UI, and load configuration"""
  global dashboard_page, github_page, menu_page, settings_page, khadamaty_page, github_page_list, github_page_text, msgboxError, msgboxErrorMSGLBL, msgboxErrorOKBTN
  global loadingOverlay
  global github_page_title, dashboard_page_title, menu_page_title, menu_page_settings_btn, menu_page_khadamaty_btn
  global settings_page_title, settings_page_brightness_label, settings_page_brightness_slider, settings_page_volume_label, settings_page_volume_slider
  global khadamaty_page_title, dashboard_page_label_wifi_status, dashboard_page_label_mqtt_status, dashboard_page_label_msg_count
  global dashboard_page_label_ip_address, dashboard_page_label_wifi_strength, dashboard_page_label_battery
  global wlan_sta, mqtt_client, wifiCredsJSON, mqttCredsJSON, mqttMessages, settingsJSON, pageIndex
  global last_activity_time, SCREEN_BRIGHTNESS_NORMAL, SPEAKER_VOLUME

  # Initialize M5Stack and UI
  M5.begin()
  M5.Widgets.setRotation(1)
  m5ui.init()
  
  # Initialize speaker
  try:
    M5.Speaker.begin()
    M5.Speaker.setVolume(11)
    print('Speaker initialized')
  except Exception as e:
    print(f'Speaker initialization: {e}')
  
  # Set initial brightness and activity time
  M5.Display.setBrightness(SCREEN_BRIGHTNESS_NORMAL)
  last_activity_time = time.time()
  
  # Create pages
  dashboard_page = m5ui.M5Page(bg_c=0xffffff)
  github_page = m5ui.M5Page(bg_c=0xffffff)
  menu_page = m5ui.M5Page(bg_c=0xffffff)
  settings_page = m5ui.M5Page(bg_c=0xffffff)
  khadamaty_page = m5ui.M5Page(bg_c=0xffffff)
  
  # Create UI elements on github_page page
  github_page_list = m5ui.M5List(x=2, y=22, w=315, h=215, parent=github_page)
  # Disable horizontal scrolling on the underlying LVGL object
  try:
    github_page_list._list.set_scroll_dir(lv.DIR.VER)  # Only vertical scroll

    # Disable scroll elasticity and momentum for better performance
    github_page_list._list.remove_flag(lv.obj.FLAG.SCROLL_ELASTIC)
    github_page_list._list.remove_flag(lv.obj.FLAG.SCROLL_MOMENTUM)
    
    # Add 2px padding between list items
    github_page_list._list.set_style_pad_row(2, 0)
  except:
    pass  # If method not available, skip
  github_page_text = github_page_list.add_text("text")
  github_page_title = m5ui.M5Label("Github", x=20, y=1, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=github_page)
  github_page_icon = m5ui.M5Image("/flash/res/img/github.png", x=1, y=1, rotation=0, scale_x=1, scale_y=1, parent=github_page)

  # Create UI elements on dashboard page
  dashboard_page_title = m5ui.M5Label("Dashboard", x=0, y=0, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_wifi_status = m5ui.M5Label("WiFi: Initializing...", x=10, y=30, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_mqtt_status = m5ui.M5Label("MQTT: Initializing...", x=10, y=50, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_msg_count = m5ui.M5Label("Messages: 0", x=10, y=70, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_ip_address = m5ui.M5Label("IP: ---.---.---.---", x=10, y=90, text_c=0x0000ff, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_wifi_strength = m5ui.M5Label("Signal: --- dBm", x=10, y=110, text_c=0x008000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
  dashboard_page_label_battery = m5ui.M5Label("Battery: ---%", x=10, y=130, text_c=0xff6600, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard_page)
    # Create UI elements on menu page
  menu_page_title = m5ui.M5Label("Menu", x=140, y=10, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_16, parent=menu_page)
  menu_page_settings_btn = m5ui.M5Button(text="Settings", x=60, y=60, w=200, h=50, bg_c=0x0066cc, text_c=0xffffff, font=lv.font_montserrat_16, parent=menu_page)
  menu_page_khadamaty_btn = m5ui.M5Button(text="Khadamaty", x=60, y=130, w=200, h=50, bg_c=0x0066cc, text_c=0xffffff, font=lv.font_montserrat_16, parent=menu_page)
  
  # Create UI elements on settings page
  settings_page_title = m5ui.M5Label("Settings", x=120, y=10, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_16, parent=settings_page)
  
  # Brightness slider
  settings_page_brightness_label = m5ui.M5Label("Max Brightness: 78%", x=20, y=50, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=settings_page)
  settings_page_brightness_slider = lv.slider(settings_page)
  settings_page_brightness_slider.set_pos(20, 75)
  settings_page_brightness_slider.set_size(280, 10)
  settings_page_brightness_slider.set_range(127, 255)  # 50% to 100%
  settings_page_brightness_slider.set_value(200, 0)
  settings_page_brightness_slider.add_event_cb(settings_brightness_slider_event, lv.EVENT.ALL, None)
  
  # Volume slider
  settings_page_volume_label = m5ui.M5Label("Volume: 73%", x=20, y=110, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=settings_page)
  settings_page_volume_slider = lv.slider(settings_page)
  settings_page_volume_slider.set_pos(20, 135)
  settings_page_volume_slider.set_size(280, 10)
  settings_page_volume_slider.set_range(0, 11)  # 0 (mute) to 11 (max)
  settings_page_volume_slider.set_value(8, 0)
  settings_page_volume_slider.add_event_cb(settings_volume_slider_event, lv.EVENT.ALL, None)
  
  # Create UI elements on khadamaty page
  khadamaty_page_title = m5ui.M5Label("Khadamaty", x=110, y=10, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_16, parent=khadamaty_page)
    # Create loading overlay using the LoadingOverlay class
  loadingOverlay = LoadingOverlay(dashboard_page)
  
  # Test image loading
  try:
    print('Test image loaded from flash')
  except Exception as e:
    print(f'Test image failed to load: {e}')
    sys.print_exception(e)
    # Try SD card fallback
 

  # Create global error dialog (accessible on all pages)
  msgboxError = m5ui.M5Msgbox(title="Error", x=61, y=60, w=200, h=180)
  msgboxErrorMSGLBL = msgboxError.add_text("Error message will appear here")
  msgboxErrorOKBTN = msgboxError.add_button(text="OK", option="footer")
  msgboxError.add_close_button()
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, True)  # Hide by default

  # Setup event handlers
  msgboxErrorOKBTN.add_event_cb(msgboxErrorOKBTN_event_handler, lv.EVENT.ALL, None)
  menu_page_settings_btn.add_event_cb(menu_settings_btn_clicked_event, lv.EVENT.CLICKED, None)
  menu_page_khadamaty_btn.add_event_cb(menu_khadamaty_btn_clicked_event, lv.EVENT.CLICKED, None)
  BtnA.setCallback(type=BtnA.CB_TYPE.WAS_CLICKED, cb=btnA_wasClicked_event)
  BtnB.setCallback(type=BtnB.CB_TYPE.WAS_CLICKED, cb=btnB_wasClicked_event)
  BtnC.setCallback(type=BtnC.CB_TYPE.WAS_CLICKED, cb=btnC_wasClicked_event)

  # Initialize SD card
  try:
    sdcard.SDCard(slot=2, width=1, sck=18, miso=38, mosi=23, cs=4, freq=1000000)
    print('SD card initialized')
  except Exception as e:
    print(f'ERROR: SD card init failed: {e}')
    sys.print_exception(e)
  
  # Initialize WiFi
  wlan_sta = network.WLAN(network.STA_IF)
  wlan_sta.config(reconnects=3)
  
  # Load configuration files from SD card
  wifiCredsJSON = readSDFile('wifi.json', True)
  mqttCredsJSON = readSDFile('mqtt.json', True)
  settingsJSON = loadSettings()
  
  # Update sliders with loaded settings
  if settingsJSON:
    settings_page_brightness_slider.set_value(settingsJSON.get('max_brightness', 200), 0)
    settings_page_brightness_label.set_text(f"Max Brightness: {int(settingsJSON.get('max_brightness', 200)/255*100)}%")
    
    volume = settingsJSON.get('volume', 8)
    settings_page_volume_slider.set_value(volume, 0)
    if volume == 0:
      settings_page_volume_label.set_text('Volume: Muted')
    else:
      settings_page_volume_label.set_text(f'Volume: {int(volume/11*100)}%')
  
  # Show dashboard
  dashboard_page.screen_load()
  
  # Display loaded config (for debugging)
  if wifiCredsJSON:
    dashboard_page_label_wifi_status.set_text('WiFi: Config loaded')
  else:
    dashboard_page_label_wifi_status.set_text('WiFi: No config found')
  
  # Load MQTT messages
  mqttMessages = loadMQTTMessages()
  
  # Update github list with loaded messages
  if mqttMessages:
    updateGitHubList()
    print(f'Loaded and displayed {len(mqttMessages)} cached messages')
  
  # Connect to WiFi if config available
  if wifiCredsJSON:
    connectWifi(wifiCredsJSON)

  # Initialize MQTT client if credentials are available and WiFi is connected
  if mqttCredsJSON and wlan_sta.isconnected():
    if not connectMQTT():
      reportError('MQTT connection failed')
  
  pageIndex = 0
  print('Setup complete')


def loop():
  """Main application loop - runs continuously"""
  global wlan_sta, mqtt_client, dashboard_page_label_wifi_status, dashboard_page_label_mqtt_status, dashboard_page_label_msg_count
  global dashboard_page_label_ip_address, dashboard_page_label_wifi_strength, dashboard_page_label_battery, wifiCredsJSON, mqttCredsJSON
  global last_activity_time
  
  M5.update()
  
  # Check for screen touch to wake display
  if M5.Touch.getCount() > 0:
    wakeScreen()
  
  # Auto-dim screen based on inactivity (only when on battery power)
  if last_activity_time:
    # Check if device is on external power
    try:
      is_charging = M5.Power.isCharging()
    except:
      is_charging = False  # Assume battery if unable to detect
    
    if is_charging:
      # Keep screen at full brightness when plugged in
      current_brightness = M5.Display.getBrightness()
      if current_brightness != SCREEN_BRIGHTNESS_NORMAL:
        M5.Display.setBrightness(SCREEN_BRIGHTNESS_NORMAL)
        print('On external power - screen stays bright')
    else:
      # On battery - apply dimming logic
      elapsed = time.time() - last_activity_time
      current_brightness = M5.Display.getBrightness()
      
      if elapsed > SCREEN_OFF_TIMEOUT:
        # Turn off backlight after timeout
        if current_brightness != 0:
          M5.Display.setBrightness(0)
          print(f'Screen off after {elapsed:.0f}s inactivity (battery)')
      elif elapsed > SCREEN_DIM_TIMEOUT:
        # Dim screen after timeout
        if current_brightness != SCREEN_BRIGHTNESS_DIM:
          M5.Display.setBrightness(SCREEN_BRIGHTNESS_DIM)
          print(f'Screen dimmed after {elapsed:.0f}s inactivity (battery)')
  
  # Check for incoming MQTT messages
  if mqtt_client:
    try:
      mqtt_client.check_msg()
    except Exception as e:
      print(f'MQTT check_msg error: {e}')
      # Mark client as disconnected on error
      mqtt_client = None
  
  # Update dashboard info every 10 seconds
  if checkTime(10):
    # Update connection status
    wifi_status = 'Connected' if wlan_sta.isconnected() else 'Disconnected'
    mqtt_status = 'Connected' if mqtt_client else 'Disconnected'
    msg_count = len(mqttMessages) if mqttMessages else 0
    dashboard_page_label_wifi_status.set_text(f'WiFi: {wifi_status}')
    dashboard_page_label_mqtt_status.set_text(f'MQTT: {mqtt_status}')
    dashboard_page_label_msg_count.set_text(f'Messages: {msg_count}')
    
    # Update battery level
    try:
      battery_level = M5.Power.getBatteryLevel()
      is_charging = M5.Power.isCharging()
      charging_icon = ' [CHG]' if is_charging else ''
      
      # Color code based on battery level
      if battery_level >= 80:
        battery_color = 0x00ff00  # Green - High
      elif battery_level >= 50:
        battery_color = 0x80ff00  # Yellow-green - Medium
      elif battery_level >= 20:
        battery_color = 0xffa500  # Orange - Low
      else:
        battery_color = 0xff0000  # Red - Critical
      
      dashboard_page_label_battery.set_style_text_color(lv.color_hex(battery_color), 0)
      dashboard_page_label_battery.set_text(f'Battery: {battery_level}%{charging_icon}')
    except Exception as e:
      dashboard_page_label_battery.set_text('Battery: N/A')
      print(f'Error reading battery: {e}')
    
    # Update IP address
    if wlan_sta.isconnected():
      ip_info = wlan_sta.ifconfig()
      ip_address = ip_info[0]
      dashboard_page_label_ip_address.set_text(f'IP: {ip_address}')
      
      # Update WiFi signal strength
      try:
        rssi = wlan_sta.status('rssi')
        # Color code based on signal strength
        if rssi >= -50:
          signal_color = 0x00ff00  # Green - Excellent
          signal_text = 'Excellent'
        elif rssi >= -60:
          signal_color = 0x80ff00  # Yellow-green - Good
          signal_text = 'Good'
        elif rssi >= -70:
          signal_color = 0xffa500  # Orange - Fair
          signal_text = 'Fair'
        else:
          signal_color = 0xff0000  # Red - Weak
          signal_text = 'Weak'
        
        dashboard_page_label_wifi_strength.set_style_text_color(lv.color_hex(signal_color), 0)
        dashboard_page_label_wifi_strength.set_text(f'Signal: {rssi} dBm ({signal_text})')
      except Exception as e:
        dashboard_page_label_wifi_strength.set_text(f'Signal: N/A')
        print(f'Error reading WiFi signal: {e}')
    else:
      dashboard_page_label_ip_address.set_text('IP: Not connected')
      dashboard_page_label_wifi_strength.set_text('Signal: Not connected')
  
  # Check WiFi and MQTT connection every 30 seconds for reconnection
  if checkTime(30):
    # Reconnect WiFi if disconnected
    if not wlan_sta.isconnected() and wifiCredsJSON:
      print('WiFi disconnected, reconnecting...')
      connectWifi(wifiCredsJSON)
    
    # Reconnect MQTT if disconnected but WiFi is connected
    if not mqtt_client and wlan_sta.isconnected() and mqttCredsJSON:
      print('MQTT disconnected, reconnecting...')
      connectMQTT()
  
  # Update list display periodically (optional, only if needed)
  # if checkTime(60):
  #   updateGitHubList()


if __name__ == '__main__':
  try:
    setup()
    while True:
      loop()
  except (Exception, KeyboardInterrupt) as e:
    print(f'\nFATAL ERROR: {e}')
    try:
      sys.print_exception(e)
    except:
      pass
    try:
      m5ui.deinit()
      from utility import print_error_msg
      print_error_msg(e)
    except ImportError:
      print("Please update to latest firmware")
    except Exception as cleanup_error:
      print(f"Cleanup error: {cleanup_error}")
