"""
M5Stack Core 2 - UIFlow2 Application
Generated by UIFlow2 GUI Web IDE

IMPORTANT: Uses M5UI (m5ui + lvgl) library - NOT M5GFX
Features:
- WiFi connectivity from SD card config
- MQTT integration
- SD card file reading
- Multi-page UI with LVGL
"""

import os, sys, io
import M5
from M5 import BtnA
import m5ui
import lvgl as lv
from hardware import sdcard
import time
import network
import json
from umqtt.simple import MQTTClient



# UI Components (global - used across multiple functions)
dashboard = None  # type: m5ui.M5Page
github = None  # type: m5ui.M5Page
github_list = None  # type: m5ui.M5List
text = None  # type: m5ui.M5TextItem
msgboxError = None  # type: m5ui.M5Msgbox
msgboxErrorMSGLBL = None  # type: m5ui.M5TextItem
msgboxErrorOKBTN = None  # type: m5ui.M5Button
msgboxLoading = None  # type: m5ui.M5Msgbox
msgboxLoadingLabel = None  # type: m5ui.M5TextItem
msgboxLoadingSpinner = None  # type: m5ui.M5Spinner
github_page_title = None  # type: m5ui.M5Label
dashboard_page_title = None  # type: m5ui.M5Label
label0 = None  # type: m5ui.M5Label
label_kzz = None  # type: m5ui.M5TextItem

# Network and Configuration (global - shared state)
wlan_sta = None  # type: network.WLAN
mqtt_client = None  # type: MQTTClient
wifiCredsJSON = None  # type: list
mqttCredsJSON = None  # type: dict
mqttMessages = None
pageIndex = None  # type: int


def reportError(errorMessage):
  """Display error message in UI msgbox"""
  global msgboxError, msgboxErrorMSGLBL, github_page_title
  print('Error:', errorMessage)
  msgboxErrorMSGLBL.set_text(str(errorMessage))
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, False)
  github_page_title.set_text(str(errorMessage))

def showLoading(show, title):
  """Show/hide loading indicator with spinner"""
  global msgboxLoading, msgboxLoadingLabel
  if show:
    print('Loading:', title)
    msgboxLoadingLabel.set_text(str(title))
    msgboxLoading.set_flag(lv.obj.FLAG.HIDDEN, False)
  else:
    print('Loading complete')
    msgboxLoading.set_flag(lv.obj.FLAG.HIDDEN, True)

def checkTime(x):
  """Check if current time is divisible by x (for periodic tasks)"""
  # No globals needed - pure function
  return (time.time()) % (int(x)) == 0


def readSDFile(fileName, returnJSON):
  """
  Read file from SD card
  Args:
    fileName: Name of file in /sd/ directory
    returnJSON: If True, parse as JSON and return dict/list, else return string
  Returns:
    Parsed JSON object or string, None on error
  """
  # No globals needed - all variables are local
  showLoading(True, f'Loading {fileName}')
  try:
    with open('/sd/' + str(fileName), 'r') as ffile:
      fileLines = ffile.readlines()
    
    fileString = ''
    for line in fileLines:
      if len(line.strip()) > 0:
        fileString += line.strip()
    
    fileString = fileString.strip()
    returnValue = json.loads(fileString) if returnJSON else fileString
    print(f'Successfully loaded {fileName}')
  except Exception as e:
    print(f'ERROR in readSDFile: {e}')
    sys.print_exception(e)
    reportError(f'Failed to load {fileName}: {e}')
    returnValue = [] if returnJSON else None
  
  showLoading(False, '')
  return returnValue


def connectWifi(credentials):
  """
  Connect to WiFi using credentials from config
  Args:
    credentials: List of dicts with 'ssid' and 'password' keys
  """
  global wlan_sta, label0
  
  # Build WiFi credentials map (local variable)
  wifi_map = {}
  for cred in credentials:
    wifi_map[cred['ssid']] = cred['password']
    showLoading(True, f"Checking: {cred['ssid']}")
    time.sleep(1)
  
  wlan_sta.config(reconnects=5)
  wlan_sta.config(dhcp_hostname='m5stack')
  
  # Scan and connect to available network
  showLoading(True, 'Scanning for networks...')
  while not wlan_sta.isconnected():
    for sta_record in wlan_sta.scan():
      ssid = sta_record[0].decode()
      if ssid in wifi_map:
        wlan_sta.active(False)
        wlan_sta.active(True)
        showLoading(True, f'Connecting to {ssid}')
        wlan_sta.connect(ssid, wifi_map[ssid])
        time.sleep(5)
        if wlan_sta.isconnected():
          print(f'Connected to {ssid}')
          showLoading(True, f'Connected: {ssid}')
          time.sleep(3)
          return
  


def updateGitHubList():
  """Update github_list with cached GitHub messages"""
  global github_list, mqttMessages
  
  try:
    # Clear existing list items
    github_list.clean()
    github_list.set_style_pad_bottom(0, 0)
    github_list.set_style_pad_top(0, 0)
    github_list.set_style_pad_left(0, 0)
    github_list.set_style_pad_right(0, 0)
    
    # Add cached messages to list
    if mqttMessages:
      for i, msg in enumerate(mqttMessages):
        # Get display text from lines array
        if 'lines' in msg and len(msg['lines']) > 0:
          display_text = '\n'.join(msg['lines'])
        else:
          display_text = f"{msg.get('repository', 'Unknown')} - {msg.get('type', 'event')}"
        
        # Get colors from message
        text_color = int(msg.get('color', '0x000000'), 16) if isinstance(msg.get('color'), str) else msg.get('color', 0x000000)
        bg_color = int(msg.get('bgColor', '0xffffff'), 16) if isinstance(msg.get('bgColor'), str) else msg.get('bgColor', 0xffffff)
        
        # Create a container for this list item (icon + text)
        list_item = lv.obj(github_list)
        list_item.set_width(310)  # Fixed width (list width minus padding)
        list_item.set_height(lv.SIZE_CONTENT)  # Auto height based on children
        list_item.set_style_bg_color(lv.color_hex(bg_color), 0)
        list_item.set_style_bg_opa(255, 0)
        list_item.set_style_border_width(0, 0)
        list_item.set_style_pad_all(5, 0)
        # list_item.set_style_pad_row(5, 0)
        # list_item.set_style_pad_column(5, 0)
        list_item.set_style_margin_bottom(0, 0)
        list_item.set_style_margin_left(0, 0)
        list_item.set_style_margin_right(0, 0)
        list_item.set_style_margin_top(0, 0)

        list_item.set_flex_flow(lv.FLEX_FLOW.ROW)
        list_item.set_flex_align(lv.FLEX_ALIGN.START, lv.FLEX_ALIGN.CENTER, lv.FLEX_ALIGN.START)
        
        # Add icon image to the container
        try:
          icon_path = msg.get('icon', 'github.png')
          icon_path = f'/flash/res/img/{icon_path}' if not icon_path.startswith('/') else icon_path
          icon = m5ui.M5Image(icon_path, x=0, y=0, rotation=0, scale_x=1.2, scale_y=1.2, parent=list_item)
        except Exception as e:
          print(f'Icon load failed for item {i}: {e}')
        
        # Add text label next to the icon (flexbox will position it automatically)
        text_label = lv.label(list_item)
        text_label.set_text(display_text[:200])  # Limit text length
        text_label.set_width(280)  # Available width for text (adjusted for container width)
        text_label.set_style_text_color(lv.color_hex(text_color), 0)
        text_label.set_style_text_font(lv.font_montserrat_14, 0)
        text_label.set_style_pad_left(5, 0)  # Space between icon and text
        
    print(f'Updated github_list with {len(mqttMessages) if mqttMessages else 0} messages')
    
  except Exception as e:
    print(f'ERROR in updateGitHubList: {e}')
    sys.print_exception(e)

def loadMQTTMessages():
  """Load MQTT messages from SD card"""
  global github_page_title
  
  messages = readSDFile('mqtt-messages.json', True)
  if messages:
    github_page_title.set_text('MQTT Messages Loaded')
  return messages


def mqtt_callback(topic, msg):
  """Handle incoming MQTT messages"""
  print(f'MQTT Message - Topic: {topic.decode()}, Message: {msg.decode()}')
  handleMQTTMessage(topic.decode(), msg.decode())


def handleMQTTMessage(topic, message):
  """
  Process received MQTT messages
  Args:
    topic: The MQTT topic as string
    message: The message payload as string
  """
  global github_page_title, label0, mqttMessages
  
  print(f'Processing MQTT - Topic: {topic}, Message: {message}')
  
  try:
    # Try to parse message as JSON
    msg_data = json.loads(message)
    
    # Check if this is a GitHub event message
    if isinstance(msg_data, dict) and msg_data.get('messageType') == 'event' and msg_data.get('messageGroup') == 'github':
      handleGitHubMessage(msg_data)
    else:
      # Handle other message types
      if isinstance(msg_data, dict):
        display_text = f"Topic: {topic}\n"
        for key, value in msg_data.items():
          display_text += f"{key}: {value}\n"
        label0.set_text(display_text[:100])
      else:
        label0.set_text(f"{topic}:\n{str(msg_data)[:80]}")
      
      github_page_title.set_text(f"Latest: {topic}")
    
  except json.JSONDecodeError:
    # Message is not JSON, display as plain text
    label0.set_text(f"{topic}:\n{message[:80]}")
    github_page_title.set_text(f"Msg: {message[:20]}")
  except Exception as e:
    print(f'ERROR in handleMQTTMessage: {e}')
    sys.print_exception(e)


def handleGitHubMessage(msg_data):
  """
  Handle GitHub event messages with caching and deduplication
  Args:
    msg_data: Parsed message data dict
  """
  global mqttMessages, github_page_title
  
  try:
    # Extract unique ID
    msg_id = msg_data.get('id')
    if not msg_id:
      print('WARNING: GitHub message has no id field')
      return
    
    # Initialize mqttMessages if needed
    if mqttMessages is None:
      mqttMessages = []
    
    # Remove existing message with same ID (to override)
    mqttMessages = [m for m in mqttMessages if m.get('id') != msg_id]
    
    # Add new message at the beginning (latest first)
    mqttMessages.insert(0, msg_data)
    
    # Keep only last 15 messages
    mqttMessages = mqttMessages[:15]
    
    # Save to SD card
    saveMQTTMessagesToSD()
    
    # Update the github list with latest messages
    updateGitHubList()
    
    # Update UI
    if 'lines' in msg_data and len(msg_data['lines']) > 0:
      display_text = '\n'.join(msg_data['lines'][:3])  # Show first 3 lines
      github_page_title.set_text(display_text[:50])
    else:
      github_page_title.set_text(f"GitHub: {msg_data.get('repository', 'event')}")
    
    print(f"GitHub message cached: ID={msg_id}, Total messages={len(mqttMessages)}")
    
  except Exception as e:
    print(f'ERROR in handleGitHubMessage: {e}')
    sys.print_exception(e)


def saveMQTTMessagesToSD():
  """Save cached MQTT messages to SD card"""
  global mqttMessages
  
  try:
    if mqttMessages is None:
      return
    
    # Convert to JSON string
    json_str = json.dumps(mqttMessages)
    
    # Write to SD card
    with open('/sd/mqtt-messages.json', 'w') as f:
      f.write(json_str)
    
    print(f'Saved {len(mqttMessages)} messages to SD card')
    
  except Exception as e:
    print(f'ERROR saving MQTT messages to SD: {e}')
    sys.print_exception(e)


# Event Handlers
def msgboxErrorOKBTN_released_event(event_struct):
  """Handle error dialog OK button click"""
  global msgboxError
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, True)


def btnA_wasClicked_event(state):
  """Handle Button A click - switch to github page"""
  global github
  github.screen_load()


def msgboxErrorOKBTN_event_handler(event_struct):
  """LVGL event handler wrapper for error OK button"""
  # No globals needed - delegates to msgboxErrorOKBTN_released_event
  event = event_struct.code
  if event == lv.EVENT.RELEASED:
    msgboxErrorOKBTN_released_event(event_struct)
  return

def setup():
  """Initialize M5Stack, UI, and load configuration"""
  global dashboard, github, github_list, text, msgboxError, msgboxErrorMSGLBL, msgboxErrorOKBTN
  global msgboxLoading, msgboxLoadingLabel, msgboxLoadingSpinner
  global github_page_title, dashboard_page_title, label0, label_kzz
  global wlan_sta, mqtt_client, wifiCredsJSON, mqttCredsJSON, mqttMessages, pageIndex

  # Initialize M5Stack and UI
  M5.begin()
  M5.Widgets.setRotation(1)
  m5ui.init()
  
  # Create pages
  dashboard = m5ui.M5Page(bg_c=0xffffff)
  github = m5ui.M5Page(bg_c=0xffffff)
  
  # Create UI elements on github page
  github_list = m5ui.M5List(x=2, y=22, w=315, h=215, parent=github)
  # Disable horizontal scrolling on the underlying LVGL object
  try:
    github_list._list.set_scroll_dir(lv.DIR.VER)  # Only vertical scroll
  except:
    pass  # If method not available, skip
  text = github_list.add_text("text")
  github_page_title = m5ui.M5Label("Github", x=0, y=0, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=github)
  
  # Create UI elements on dashboard page
  dashboard_page_title = m5ui.M5Label("Dashboard", x=0, y=0, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard)
  label0 = m5ui.M5Label("Initializing...", x=62, y=57, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard)
  label_kzz = m5ui.M5Label("Line 1\nLine 2\nLine 3", x=62, y=120, text_c=0x000000, bg_c=0xffffff, bg_opa=0, font=lv.font_montserrat_14, parent=dashboard)
  
  # Test image loading
  try:
    test_image = m5ui.M5Image("/flash/res/img/github.png", x=10, y=180, rotation=0, scale_x=1, scale_y=1, parent=dashboard)
    print('Test image loaded from flash')
  except Exception as e:
    print(f'Test image failed to load: {e}')
    sys.print_exception(e)
    # Try SD card fallback
    try:
      test_image = m5ui.M5Image("/sd/github.png", x=10, y=180, rotation=0, scale_x=1, scale_y=1, parent=dashboard)
      print('Test image loaded from SD card')
    except Exception as e2:
      print(f'Test image SD fallback failed: {e2}')
      sys.print_exception(e2)

  # Create global error dialog (accessible on all pages)
  msgboxError = m5ui.M5Msgbox(title="Error", x=61, y=60, w=200, h=180)
  msgboxErrorMSGLBL = msgboxError.add_text("Error message will appear here")
  msgboxErrorOKBTN = msgboxError.add_button(text="OK", option="footer")
  msgboxError.add_close_button()
  msgboxError.set_flag(lv.obj.FLAG.HIDDEN, True)  # Hide by default

  # Create global loading dialog (accessible on all pages)
  msgboxLoading = m5ui.M5Msgbox(title="Loading", x=61, y=60, w=200, h=150)
  msgboxLoadingLabel = msgboxLoading.add_text("Please wait...")
  msgboxLoadingSpinner = m5ui.M5Spinner(x=85, y=90, w=30, h=30, parent=msgboxLoading)
  msgboxLoading.set_flag(lv.obj.FLAG.HIDDEN, True)  # Hide by default

  # Setup event handlers
  msgboxErrorOKBTN.add_event_cb(msgboxErrorOKBTN_event_handler, lv.EVENT.ALL, None)
  BtnA.setCallback(type=BtnA.CB_TYPE.WAS_CLICKED, cb=btnA_wasClicked_event)

  # Initialize SD card
  try:
    sdcard.SDCard(slot=2, width=1, sck=18, miso=38, mosi=23, cs=4, freq=1000000)
    print('SD card initialized')
  except Exception as e:
    print(f'ERROR: SD card init failed: {e}')
    sys.print_exception(e)
  
  # Initialize WiFi
  wlan_sta = network.WLAN(network.STA_IF)
  wlan_sta.config(reconnects=3)
  
  # Load configuration files from SD card
  wifiCredsJSON = readSDFile('wifi.json', True)
  mqttCredsJSON = readSDFile('mqtt.json', True)
  
  # Show dashboard
  dashboard.screen_load()
  
  # Display loaded config (for debugging)
  if wifiCredsJSON:
    label0.set_text('WiFi config loaded')
  else:
    label0.set_text('No WiFi config found')
  
  # Load MQTT messages
  mqttMessages = loadMQTTMessages()
  
  # Update github list with loaded messages
  if mqttMessages:
    updateGitHubList()
    print(f'Loaded and displayed {len(mqttMessages)} cached messages')
  
  # Connect to WiFi if config available
  if wifiCredsJSON:
    connectWifi(wifiCredsJSON)
  showLoading(False, '')

  # Initialize MQTT client if credentials are available and WiFi is connected
  if mqttCredsJSON and wlan_sta.isconnected():
    try:
      showLoading(True, 'Connecting to MQTT...')
      mqtt_client = MQTTClient(
        mqttCredsJSON['client'],
        mqttCredsJSON['server'],
        port=int(mqttCredsJSON['port']),
        user=mqttCredsJSON['username'],
        password=mqttCredsJSON['password'],
        keepalive=1000,
        ssl=True,
        ssl_params={"server_hostname": mqttCredsJSON['server']}
      )
      mqtt_client.set_callback(mqtt_callback)
      mqtt_client.connect()
      
      # Subscribe to a topic (you can change this to your desired topic)
      topic = mqttCredsJSON.get('topic', 'm5stack-notifications/github/all')
      mqtt_client.subscribe(topic)
      print(f'MQTT connected and subscribed to {topic}')
      showLoading(False, '')
    except Exception as e:
      print(f'ERROR: MQTT setup failed: {e}')
      sys.print_exception(e)
      reportError(f'MQTT connection failed: {e}')
      showLoading(False, '')
  
  pageIndex = 0
  print('Setup complete')


def loop():
  """Main application loop - runs continuously"""
  global wlan_sta, mqtt_client, label0, wifiCredsJSON
  
  M5.update()
  
  # Check for incoming MQTT messages
  if mqtt_client:
    try:
      mqtt_client.check_msg()
    except Exception as e:
      print(f'MQTT check_msg error: {e}')
  
  # Check WiFi connection every 30 seconds
  if checkTime(30):
    status = 'Connected' if wlan_sta.isconnected() else 'Disconnected'
    label0.set_text(f'{status} - {time.time()}')
    
    # Reconnect if disconnected
    if not wlan_sta.isconnected() and wifiCredsJSON:
      print('WiFi disconnected, reconnecting...')
      connectWifi(wifiCredsJSON)
  
  # Update list display periodically (optional, only if needed)
  # if checkTime(60):
  #   updateGitHubList()


if __name__ == '__main__':
  try:
    setup()
    while True:
      loop()
  except (Exception, KeyboardInterrupt) as e:
    print(f'\nFATAL ERROR: {e}')
    try:
      sys.print_exception(e)
    except:
      pass
    try:
      m5ui.deinit()
      from utility import print_error_msg
      print_error_msg(e)
    except ImportError:
      print("Please update to latest firmware")
    except Exception as cleanup_error:
      print(f"Cleanup error: {cleanup_error}")
